version: '3'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: nginx
    env_file: edge-env
    networks:
      - back
    ports:
      - '8000:8000'
    volumes:
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './config/nginx/mc-edge.conf:/etc/nginx/mc-edge.conf'
    restart: always
    depends_on:
      - nodered
      - graphite
      - grafana
  graphite:
    image: 'graphiteapp/graphite-statsd:1.1.4'
    container_name: graphite
    env_file: edge-env
    networks:
      - back
    ports:
      - '8080:80'
      - '2003-2004:2003-2004'
      - '2023-2024:2023-2024'
      - '8125:8125/udp'
      - '8126:8126'
    volumes:
      - './config/graphite/local_settings.py:/opt/graphite/webapp/graphite/local_settings.py'
      - './config/graphite/carbon.conf:/opt/graphite/conf/carbon.conf'
      - './config/graphite/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf'
      - './config/graphite/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf'
      - './config/graphite/statsd-config.js:/opt/statsd/config_udp.js'
    restart: always
  mqtt:
    image: 'eclipse-mosquitto:1.5'
    container_name: mqtt
    env_file: edge-env
    networks:
      - back
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - './config/mqtt:/mosquitto/config'
    restart: always
  nodered:
    image: 'lorenwest/iot-edge-node-red:prod'
    container_name: nodered
    env_file: edge-env
    depends_on:
      - mqtt
    networks:
      - front
      - back
    ports:
      - '1880:1880'
    volumes:
      - './config/node-red/settings.js:/data/settings.js'
    restart: always
    depends_on:
      - "mqtt"
  grafana:
    image: 'grafana/grafana:5.3.4'
    container_name: grafana
    env_file:
      - edge-env
    networks:
      - back
    ports:
      - '3000:3000'
    volumes:
      - './config/grafana:/etc/grafana'
      - './config/grafana:/usr/share/grafana/public/mc-grafana'
    restart: always
  edge:
    image: 'lorenwest/iot-edge-node-js'
    container_name: edge
    env_file:
      - edge-env
    networks:
      - back
      - front
    ports:
      - '9002:9002'
    volumes:
      - './config/grafana:/etc/grafana'
      - './config/grafana:/usr/share/grafana/public/mc-grafana'
    depends_on:
      - "grafana"
    restart: always
    environment:
      - NODE_ENV=production
    working_dir: ./edge/node_modules/iot-edge
    entrypoint:
      -  node
      -  app.js
networks:
  front:
    driver: bridge
  back: null
