server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /promdata/positions.yaml

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: dockerlogs
      __path__: /promdata/log/*log
